xcodeproj 'PINRemoteImage.xcodeproj'

target 'PINRemoteImage', :exclusive => true do
  pod "PINRemoteImage/iOS", :path => "../"
  pod "PINRemoteImage/WebP", :path => "../"
  pod "PINCache"
end

target 'PINRemoteImage Tests', :exclusive => true do
  pod "PINRemoteImage/WebP", :path => "../"
end
