xcodeproj 'PINRemoteImage.xcodeproj'

target 'PINRemoteImage', :exclusive => true do
  pod "PINRemoteImage", :path => "../"
  pod "PINRemoteImage/WebP", :path => "../"
end

target 'PINRemoteImage Tests', :exclusive => true do
  pod "PINRemoteImage/WebP", :path => "../"
end
