target 'PINRemoteImage', :exclusive => true do
  pod "PINRemoteImage/FLAnimatedImage", :path => "../"
  pod "PINCache"
  pod "libwebp"
end

target 'PINRemoteImage Tests', :exclusive => true do
  pod "PINRemoteImage/FLAnimatedImage", :path => "../"
end
