target 'PINRemoteImage' do
  pod "PINRemoteImage/OSX", :path => "../../"
  pod "PINRemoteImage/WebP", :path => "../../"
  pod "PINRemoteImage/PINCache", :path => "../../"
  pod "PINCache"
  pod "libwebp"
end
