platform :macos, 10.11

target 'Example-Mac' do
  pod "PINRemoteImage/OSX", :path => "../../"
  pod "PINRemoteImage/WebP", :path => "../../"
  pod "PINRemoteImage/PINCache", :path => "../../"
  pod "PINCache"
  pod "libwebp"
end
