xcodeproj 'PINRemoteImage.xcodeproj'
platform :ios, 8.0

def shared_pods
  pod "PINRemoteImage", :path => "../../"
  pod "PINRemoteImage/WebP", :path => "../../"
  pod "PINRemoteImage/PINCache", :path => "../../"
end

target 'PINRemoteImage' do
  shared_pods
end
